### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by liuyueChang** [vita-epfl/RRB#9]
Thank you for your outstanding work!
I am using this raw code to train the model, but I encountered the Segmentation fault
I did not make any changes to the code and executed run.sh according to readme's requirements
Every time the program prompts an error halfway through training.
![image](https://github.com/vita-epfl/RRB/assets/112742491/231ec7f2-67ea-4a5b-adc5-9c065449d122)

Here is my environment

absl-py                 1.4.0               
cachetools              4.2.4               
casadi                  3.6.3               
certifi                 2021.5.30           
charset-normalizer      2.0.12              
cycler                  0.11.0              
dataclasses             0.8                 
google-auth             2.19.0              
google-auth-oauthlib    0.4.6               
grpcio                  1.48.2              
idna                    3.4                 
importlib-metadata      4.8.3               
kiwisolver              1.3.1               
Markdown                3.3.7               
matplotlib              3.3.4               
mkl-fft                 1.2.0               
mkl-random              1.2.0               
mkl-service             2.3.0               
numpy                   1.19.2              
oauthlib                3.2.2               
olefile                 0.46                
opencv-python-headless  3.4.10.35           
Pillow                  8.2.0               
pip                     20.0.2              
protobuf                3.19.6              
pyasn1                  0.5.0               
pyasn1-modules          0.3.0               
pykalman                0.9.5               
pyparsing               3.0.9               
python-dateutil         2.8.2               
python-json-logger      2.0.7               
requests                2.27.1              
requests-oauthlib       1.3.1               
rsa                     4.9                 
scipy                   1.5.4               
setuptools              49.6.0.post20210108 
six                     1.16.0              
tensorboard             2.10.1              
tensorboard-data-server 0.6.1               
tensorboard-plugin-wit  1.8.1               
torch                   1.10.0              
torchaudio              0.10.0              
torchvision             0.11.0              
trajnettools            0.1.0              
typing-extensions       4.1.1               
urllib3                 1.26.16             
Werkzeug                2.0.3               
wheel                   0.36.2              
zipp                    3.6.0

**Comment by MohammadHossein-Bahari** [comment]
Hello,
Thanks for your interest in the project!
The issue is because of memory shortage. Your machine's memory is not enough (to clarify, we are talking about CPU memory).
If you are using a cluster, request more memory. In the case of a workstation, you need to try a machine with more memory.

**Comment by liuyueChang** [comment]
ok, thank you very much!
